<!-- ------------------------------------------------------------------- --
  -- END of document:  Below this must not be anything, except the stuff --
  -- concerning the table of abbreviations                               --> 
  

```{r WriteTableOfAbbreviations, echo=FALSE, results='hide', eval=FALSE}
if (!r6objTableAbbrev$is_empty_abbr())
  r6objTableAbbrev$writeToTsvFile()
```

```{r AbrTableToDocument, echo=FALSE, results='asis', eval=FALSE}
r6objTableAbbrev$include_abbr_table(psAbbrTitle = "# Abkürzungen {-}")
```


```{r Bibliography, echo=FALSE, results='hide'}
bref <- c(bibentry(
    bibtype = "Unpublished",
    title   = "Quantitative Genetik und Zuchtplanung",
    author  = as.person("K-U. Götz [aut]"),
    year    = "2014",
    note    = "Bayerische Landesanstalt für Landwirtschaft, Institut für Tierzucht",
    key     = "Goetz2014"
  ),
  bibentry(
    bibtype   = "Book",
    title     = "Tierzucht — Grundwissen Bachelor",
    author    = c(as.person("A. Willam"), as.person("H. Simianer")),
    year      = "2011",
    publisher = "Ulmer UTB 3526",
    key       = "WS2011"
  ),
  bibentry(
    bibtype = "Book",
    title = "Introduction To Quantitative Genetics",
    author = c(as.person("D.F. Falconer"), as.person("T.F.C. Mackay")),
    year = "1996",
    publisher = "Addison Wesley Longman",
    key = "FM1996"
  ),
  bibentry(
    bibtype = "Book",
    title = "Linear Models for the Prediction of Animal Breeding Values",
    author = as.person("R Mrode"),
    year = "2005",
    publisher = "CABI Publishing",
    key = "Mrode2005"
  ),
  bibentry(
    bibtype = "Article",
    title = "The genetic basis for constructing selection indexes",
    author = as.person("L. N. Hazel"),
    year = 1943,
    journal = "Genetics",
    volume = 28,
    page = "476-490",
    key = "Hazel1943"
  ),
  bibentry(
    bibtype = "Article",
    title = "The efficiency of three methods of selection",
    author = c(as.person("L. N. Hazel"), as.person("J. L. Lush")),
    year = 1943,
    journal = "Journal of Heredity",
    volume = 33,
    page = "393-399",
    key = "HL1943"
  ),
  bibentry(
    bibtype = "Article",
    title = "Sire evaluation and genetic trends",
    author = as.person("C. R. Henderson"),
    year = 1973,
    journal = "Proceedings of the Animal Breeding and Genetics Symposium in Honour of Dr.Jay L. Lush. ASAS and ADSA, Champaign, Ill.",
    page = "10-41",
    key = "Henderson1973"
  )
  
)

### # Fixed assignmen of bib file
sBibFile <- "GEL.bib"
if(!file.exists(sBibFile))
  cat(paste(toBibtex(bref), collapse = "\n"), "\n", file = sBibFile)
```


`r if (knitr:::is_html_output()) '# References {-}'`
